
const fakeIdea = [
  [
    {
      ideaId: 1,
      idea:" Lorem ipsum dolor sit amet, consectetur adipisicing elit. Cum veniam laboriosam quidem quae quia architecto fuga labore. Assumenda nobis aut impedit ad fugit magni libero. Ipsum dolorum totam quibusdam labore.",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "https://media-mcetv.ouest-france.fr/wp-content/uploads/2023/10/one-piece-top-5-des-plus-grandes-faiblesses-de-roronoa-zoro-.jpg",
      },
      isMod: false,
      showVote: true,
      bgColor: "hsl(142.1 70.6% 45.3%)",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
  [
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
  [
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
  [
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
  [
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
  [
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
    {
      ideaId: 1,
      idea: "Fake Idea",
      details: "This is a fake idea for demonstration purposes",
      submitter: {
        email: "fake@example.com",
        id: 123,
        name: "Fake User",
        pfp: "fake-avatar.jpg",
      },
      isMod: true,
      showVote: true,
      bgColor: "#abcdef",
      comments: [
        {
          user: {
            email: "commenter@example.com",
            id: 456,
            name: "Commenter",
            pfp: "commenter-avatar.jpg",
          },
          comment: "This is a fake comment.",
        },
      ],
      votes: 10,
      handleComment: () => {},
      handleVote: () => {},
      handleSelect: () => {},
    },
  ],
];
export default fakeIdea;
